#!/bin/sh
#
# see: dh_installdeb(1)

set -e
# postinst script for se3-wpkg
#
#  d'apres le script d'installation de Jean Le Bail
#  juillet 2008
#
## $Id$ ##


# summary of how this script can be called:
#        * <postinst> `configure' <most-recently-configured-version>
#        * <old-postinst> `abort-upgrade' <new version>
#        * <conflictor's-postinst> `abort-remove' `in-favour' <package>
#          <new-version>
#        * <postinst> `abort-remove'
#        * <deconfigured's-postinst> `abort-deconfigure' `in-favour'
#          <failed-install-package> <version> `removing'
#          <conflicting-package> <version>
# for details, see http://www.debian.org/doc/debian-policy/ or
# the debian-policy package

case "$1" in
    	install|configure)
	cd /var/cache/se3_install/
	chmod +x wpkg-install.sh
	if ( /bin/grep -q "3\.[01]" /etc/debian_version ) ; then
		## charset ISO8859-15 pour woody et sarge ##
		/usr/bin/recode UTF8..ISO8859-15 wpkg-install.sh
		/usr/bin/recode UTF8..ISO8859-15 web-wpkg-install.sh
	fi
	./wpkg-install.sh

	chown www-se3:root /usr/share/se3/scripts/wakeonlan
	chmod 750 /usr/share/se3/scripts/wakeonlan

	echo "retablissement des droits sur /var/www/se3/wpkg"
	chown -R www-se3:root /var/www/se3/wpkg

	echo "configuration de l'interface web de wpkg"
	chmod +x /var/cache/se3_install/web-wpkg-install.sh
	/var/cache/se3_install/web-wpkg-install.sh

	WWWPATH="/var/www"
	## recuperation des variables necessaires pour interoger mysql ###
	if [ -e $WWWPATH/se3/includes/config.inc.php ]; then
		dbhost=`cat $WWWPATH/se3/includes/config.inc.php | grep "dbhost=" | cut -d = -f2 | cut -d \" -f2`
		dbname=`cat $WWWPATH/se3/includes/config.inc.php | grep "dbname=" | cut	-d = -f 2 |cut -d \" -f 2`
		dbuser=`cat $WWWPATH/se3/includes/config.inc.php | grep "dbuser=" | cut -d = -f 2 | cut -d \" -f 2`
		dbpass=`cat $WWWPATH/se3/includes/config.inc.php | grep "dbpass=" | cut -d = -f 2 | cut -d \" -f 2`
	else
		echo "Fichier de configuration inaccessible, le script ne peut se poursuivre."
		exit 1
	fi
	##### Activation wpkg dans l'interface web 
	test_exist=`echo "SELECT id FROM params WHERE name='wpkg'" | mysql -h $dbhost $dbname -u $dbuser -p$dbpass -N`
	if [ "X$test_exist" = "X" ]; then # if empty
		echo "INSERT into params (name,value,srv_id,descr,cat) VALUES (\"wpkg\",\"1\",\"\",\"Activation ou désactivation de wpkg\",6) " | mysql -h $dbhost $dbname -u $dbuser -p$dbpass -N
	fi
    ;;

    abort-upgrade|abort-remove|abort-deconfigure)
    ;;

    *)
        echo "postinst called with unknown argument \`$1'" >&2
        exit 1
    ;;
esac

