#!/bin/bash
#
# see: dh_installdeb(1)

set -e
# postinst script for se3-wpkg
#
# summary of how this script can be called:
#        * <postinst> `configure' <most-recently-configured-version>
#        * <old-postinst> `abort-upgrade' <new version>
#        * <conflictor's-postinst> `abort-remove' `in-favour' <package>
#          <new-version>
#        * <postinst> `abort-remove'
#        * <deconfigured's-postinst> `abort-deconfigure' `in-favour'
#          <failed-install-package> <version> `removing'
#          <conflicting-package> <version>
# for details, see http://www.debian.org/doc/debian-policy/ or
# the debian-policy package

case "$1" in
configure)

. /usr/share/sambaedu/includes/config.inc.sh
. /usr/share/sambaedu/includes/utils.inc.sh
. /usr/share/debconf/confmodule

# recup des parametres

db_get sambaedu/wpkgroot
set_config wpkg wpkgroot "$RET"
db_get sambaedu/se3_name
set_config wpkg se3_name "$RET"

#ajout d'un alias dns	
su www-admin -c "samba-tool dns add ${config_se4ad_name} ${config_domain} ${config_se3_name} CNAME se4fs.${config_domain} -k yes" || true

/usr/share/sambaedu/scripts/wpkg-install.sh

chown www-admin:root /usr/share/sambaedu/scripts/wakeonlan
chmod 750 /usr/share/sambaedu/scripts/wakeonlan

wpkgwww="/var/www/sambaedu/wpkg"

if [ ! -d "${config_wpkgroot}/tmp" ]; then
mkdir ${config_wpkgroot}/tmp
	chown -R www-admin ${config_wpkgroot}/tmp
fi
if [ ! -e "${config_wpkgroot}/tmp/timeStamps.xml" ]; then
echo "<installations/>" > ${config_wpkgroot}/tmp/timeStamps.xml
	chown www-admin ${config_wpkgroot}/tmp/timeStamps.xml
fi
if [ ! -e "${wpkgwww}/sambaedu_wpkglist.php" ]; then
	echo "<packages/>" > ${wpkgwww}/sambaedu_wpkglist.php
chown www-admin ${wpkgwww}/sambaedu_wpkglist.php
	# Pour que le fichier soit mis à jour à la prochaine demande
	touch --date='jun 1 00:00:00 CEST 2007' ${wpkgwww}/sambaedu_wpkglist.php
fi

	chown -R www-admin:www-data $wpkgwww
	chown -R www-admin:root $config_wpkgroot
	chmod 775 ${wpkgwww}/bin/*
	chown -R www-admin /var/www/sambaedu/includes/menu.d/
;;

abort-upgrade|abort-remove|abort-deconfigure)
;;

*)
echo "postinst called with unknown argument \`$1'" >&2
exit 1
;;
esac
